ARG ARCH=
ARG DISTRO=
ARG TAG=

{FROM}

ARG VALA_NAME=

{BASE}

FROM base AS build

{BUILD}

RUN mkdir -p /opt/build /opt/src
COPY ${VALA_NAME} /opt/src
WORKDIR /opt/src
RUN ./configure --prefix=/usr --disable-valadoc CFLAGS="-O2" && \
    make -j$(getconf _NPROCESSORS_ONLN) && \
    make DESTDIR=/opt/build install-strip

FROM base AS runtime

COPY --from=build /opt/build /
