name: Build and push all

on:
  push:
    branches: [ master ]

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}

jobs:
  build-push:
    strategy:
      matrix:
        distro: [alpine, debian, elementary, fedora, ubuntu]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master
      - name: Setup Docker Multiarch
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Log-in to Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set REPO env variable
        run: |
         echo "REPO=$(echo ${REGISTRY}/${OWNER}/vala | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_ENV}"
      - name: Build and push
        run: make DISTROS=${{ matrix.distro }} BUILDFLAGS=--push
